const product = [
    {
        id: "e43638ce-6aa0-4b85-b27f-e1d07eb678c6",
        image_main: "/Cars/Corolla 2007.jpg",
        image:  ["/Cars/Corolla 2007.jpg", "/Cars/detail1.jpg", "/Cars/detail3.jpg"], 
        image_thumbnail: "/Cars/detail1.jpg",
        image_thumbnail2: "/Cars/detail1.jpg",
        image_thumbnail3: "/Cars/detail1.jpg",
        video_id: "V06rNc5JcZw",
        name: "Black Corolla London 2007",
        description: "This is a well-maintained car with a clean history. It is fuel-efficient, offers a smooth driving experience, and has been well taken care of by its previous owners.",
        brand: "Toyota",
        feature: "yes",
        Year: 2007,
        Mileage: "50,000 miles",
        engine: "2.0L, 4 Cylinder",
        priceCents: 700000000,
        agent_name: "Agent: James Emmanuel",
        agent_photo: "/Agents/agent1.jpg",
        agent_phone: "Phone: 0802307461",
        agent_email: "Email: james.emmanuel@example.com",
      },
      {
        id: "15b6fc6f-327a-4ec4-896f-486349e85a3d",
        image_main: "/Cars/Corolla 2013.jpg",
        image:  ["/Cars/Corolla 2013.jpg", "/Cars/detail3.jpg", "/Cars/detail2.jpg"], 
        image_thumbnail: "/Cars/detail1.jpg",
        image_thumbnail2: "/Cars/detail1.jpg",
        image_thumbnail3: "/Cars/detail1.jpg",
        video_id: "V06rNc5JcZw",
        name: "Gray Corolla London 2013",
        description: "This is a well-maintained car with a clean history. It is fuel-efficient, offers a smooth driving experience, and has been well taken care of by its previous owners.",
        brand: "Hundai",
        feature: "no",
        Year: 2007,
        Mileage: "50,000 miles",
        engine: "2.0L, 4 Cylinder",
        priceCents: 100000000,
        agent_name: "Isaac Bishop",
        agent_photo: "/Agents/agent2.jpg",
        agent_phone: "Phone: 0802307461",
        agent_email: "Email: james.emmanuel@example.com",
      },
      {
        id: "83d4ca15-0f35-48f5-b7a3-1ea210004f2e",
        image_main: "/Cars/Toyota.jpg.webp",
        image:  ["/Cars/Toyota.jpg.webp", "/Cars/detail1.jpg", "/Cars/detail2.jpg"], 
        image_detail1: "/Cars/detail1.jpg",
        image_detail2: "/Cars/detail2.jpg",
        image_thumbnail: "/Cars/detail1.jpg",
        image_thumbnail2: "/Cars/detail1.jpg",
        image_thumbnail3: "/Cars/detail1.jpg",
        video_id: "V06rNc5JcZw",
        name: "White Small Toyota",
        description: "This is a well-maintained car with a clean history. It is fuel-efficient, offers a smooth driving experience, and has been well taken care of by its previous owners.",
        brand: "BMW",
        feature: "yes",
        Year: 2007,
        Mileage: "50,000 miles",
        engine: "2.0L, 4 Cylinder",
        priceCents: 1500000000,
        agent_name: "Favor Bush",
        agent_photo: "/Agents/agent3.jpg",
        agent_phone: "Phone: 0802307461",
        agent_email: "Email: james.emmanuel@example.com",
      },
      {
        id: "54e0eccd-8f36-462b-b68a-8182611d9add",
        image_main: "/Cars/2013 Ford-Explorer.webp",
        image:  ["/Cars/2012 Ford-Explorer.webp", "/Cars/detail1.jpg", "/Cars/detail2.jpg"], 
        image_thumbnail: "/Cars/detail1.jpg",
        image_thumbnail2: "/Cars/detail1.jpg",
        image_thumbnail3: "/Cars/detail1.jpg",
        video_id: "V06rNc5JcZw",
        name: "Silver Ford Explorer",
        description: "This is a well-maintained car with a clean history. It is fuel-efficient, offers a smooth driving experience, and has been well taken care of by its previous owners.",
        brand: "Toyota",
        feature: "no",
        Year: 2007,
        Mileage: "50,000 miles",
        engine: "2.0L, 4 Cylinder",
        priceCents: 300000000,
        agent_name: "George Tallman",
        agent_photo: "/Agents/agent4.jpg",
        agent_phone: "Phone: 0802307461",
        agent_email: "Email: james.emmanuel@example.com",
      },
      {
        id: "3ebe75dc-64d2-4137-8860-1f5a963e534b",
        image_main: "/Cars/2018 Honda-Accord.jpg",
        image:  ["/Cars/2018 Honda-Accord.jpg", "/Cars/detail1.jpg", "/Cars/detail2.jpg"],
        image_thumbnail: "/Cars/detail1.jpg",
        image_thumbnail2: "/Cars/detail1.jpg",
        image_thumbnail3: "/Cars/detail1.jpg",
        video_id: "V06rNc5JcZw",
        name: "2018 Black Honda Accord",
        description: "This is a well-maintained car with a clean history. It is fuel-efficient, offers a smooth driving experience, and has been well taken care of by its previous owners.",
        brand: "Hundai",
        feature: "yes",
        Year: 2007,
        Mileage: "50,000 miles",
        engine: "2.0L, 4 Cylinder",
        priceCents: 2500000000,
        agent_name: "Mathew Philip",
        agent_photo: "/Agents/agent5.jpg",
        agent_phone: "Phone: 0802307461",
        agent_email: "Email: james.emmanuel@example.com",
        
      },
      {
        id: "8c9c52b5-5a19-4bcb-a5d1-158a74287c53",
        image_main: "/Cars/2022 Lexus-GX-460.jpg",
        image:  ["/Cars/Corolla 2007.jpg", "/Cars/detail1.jpg", "/Cars/detail2.jpg"], 
        image_thumbnail: "/Cars/detail1.jpg",
        image_thumbnail2: "/Cars/detail1.jpg",
        image_thumbnail3: "/Cars/detail1.jpg",
        video_id: "V06rNc5JcZw",
        name: "2022 Black Lexus GX 460",
        description: "This is a well-maintained car with a clean history. It is fuel-efficient, offers a smooth driving experience, and has been well taken care of by its previous owners.",
        brand: "BMW",
        feature: "no",
        Year: 2007,
        Mileage: "50,000 miles",
        engine: "2.0L, 4 Cylinder",
        priceCents: 500000000,
        agent_name: "Miracle Okpalaihedi",
        agent_photo: "/Agents/agent6.jpg",
        agent_phone: "Phone: 0802307461",
        agent_email: "Email: james.emmanuel@example.com",
      },
      {
        id: "dd82ca78-a18b-4e2a-9250-31e67412f98d",
        image_main: "/Cars/2023 Toyota Landcruiser-300-VXR.webp",
        image:  ["/Cars/Toyota Landcruiser-300-VXR.webp", "/Cars/detail1.jpg", "/Cars/detail2.jpg"], 
        image_thumbnail: "/Cars/detail1.jpg",
        image_thumbnail2: "/Cars/detail1.jpg",
        image_thumbnail3: "/Cars/detail1.jpg",
        video_id: "V06rNc5JcZw",
        name: "2023 Black Toyota Landcruiser 300",
        description: "This is a well-maintained car with a clean history. It is fuel-efficient, offers a smooth driving experience, and has been well taken care of by its previous owners.",
        brand: "Toyota",
        feature: "yes",
        Year: 2007,
        Mileage: "50,000 miles",
        engine: "2.0L, 4 Cylinder",
        priceCents: 800000000,
        agent_name: "Uche Okpalaihedi",
        agent_photo: "/Agents/agent7.jpg",
        agent_phone: "Phone: 0802307461",
        agent_email: "Email: james.emmanuel@example.com",
      },
      {
        id: "77919bbe-0e56-475b-adde-4f24dfed3a04",
        image_main: "/Cars/2023 Toyota-Land-Cruiser-prado.webp",
        image:  ["/Cars/2023 Toyota-Land_cruiser-prado.webp", "/Cars/detail1.jpg", "/Cars/detail2.jpg"], 
        image_thumbnail: "/Cars/detail1.jpg",
        image_thumbnail2: "/Cars/detail1.jpg",
        image_thumbnail3: "/Cars/detail1.jpg",
        video_id: "V06rNc5JcZw",
        name: "2023 Gray Toyota Land Cruiser Prado",
        description: "This is a well-maintained car with a clean history. It is fuel-efficient, offers a smooth driving experience, and has been well taken care of by its previous owners.",
        brand: "Hundai",
        feature: "no",
        Year: 2007,
        Mileage: "50,000 miles",
        engine: "2.0L, 4 Cylinder",
        priceCents: 1200000000,
        agent_name: "Favor Okpalaihedi",
        agent_photo: "/Agents/agent8.jpg",
        agent_phone: "Phone: 0802307461",
        agent_email: "Email: james.emmanuel@example.com",
      },
      {
        id: "3fdfe8d6-9a15-4979-b459-585b0d0545b9",
        image_main: "/Cars/2024 Lexus-LX-600.webp",
        image:  ["/Cars/2024 Lexus-LX-600.webp", "/Cars/detail1.jpg", "/Cars/detail2.jpg"], 
        image_thumbnail: "/Cars/detail1.jpg",
        image_thumbnail2: "/Cars/detail1.jpg",
        image_thumbnail3: "/Cars/detail1.jpg",
        video_id: "V06rNc5JcZw",
        name: "2024 Black Lexus LX 600",
        description: "This is a well-maintained car with a clean history. It is fuel-efficient, offers a smooth driving experience, and has been well taken care of by its previous owners.",
        brand: "BMW",
        feature: "yes",
        Year: 2007,
        Mileage: "50,000 miles",
        engine: "2.0L, 4 Cylinder",
        priceCents: 1300000000,
        agent_name: "Favor Okpalaihedi",
        agent_photo: "/Agents/agent1.jpg",
        agent_phone: "Phone: 0802307461",
        agent_email: "Email: james.emmanuel@example.com",
      },
      {
        id: "58b4fc92-e98c-42aa-8c55-b6b79996769a",
        image_main: "/Cars/2024 Toyota Hilux.jpg",
        image:  ["/Cars/2024 Toyota Hilux.jpg", "/Cars/detail1.jpg", "/Cars/detail2.jpg"],
        image_thumbnail: "/Cars/detail1.jpg",
        image_thumbnail2: "/Cars/detail1.jpg",
        image_thumbnail3: "/Cars/detail1.jpg",
        video_id: "V06rNc5JcZw",
        name: "2024 Black Toyota Hilux",
        description: "This is a well-maintained car with a clean history. It is fuel-efficient, offers a smooth driving experience, and has been well taken care of by its previous owners.",
        brand: "Toyota",
        feature: "no",
        Year: 2007,
        Mileage: "50,000 miles",
        engine: "2.0L, 4 Cylinder",
        priceCents: 1200000000,
        agent_name: "Favor Okpalaihedi",
        agent_photo: "/Agents/agent2.jpg",
        agent_phone: "Phone: 0802307461",
        agent_email: "Email: james.emmanuel@example.com",
      },
      {
        id: "5968897c-4d27-4872-89f6-5bcb052746d7",
        image_main: "/Cars/2024 Toyota-Land-Cruiser-GXR.jpg",
        image:  ["/Cars/2024 Toyota-Land-Crusier-GXR.jpg", "/Cars/detail1.jpg", "/Cars/detail2.jpg"],
        image_thumbnail: "/Cars/detail1.jpg",
        image_thumbnail2: "/Cars/detail1.jpg",
        image_thumbnail3: "/Cars/detail1.jpg",
        video_id: "V06rNc5JcZw",
        name: "2024 White Toyota Land Cruiser",
        description: "This is a well-maintained car with a clean history. It is fuel-efficient, offers a smooth driving experience, and has been well taken care of by its previous owners.",
        brand: "Hundai",
        feature: "yes",
        Year: 2007,
        Mileage: "50,000 miles",
        engine: "2.0L, 4 Cylinder",
        priceCents: 1500000000,
        agent_name: "Favor Okpalaihedi",
        agent_photo: "/Agents/agent3.jpg",
        agent_phone: "Phone: 0802307461",
        agent_email: "Email: james.emmanuel@example.com",
      },
      {
        id: "e43638ce-6aa0-4b85-b27f-e1d07eb678c612323-33agww",
        image_main: "/Cars/Corolla 2018.jpg",
        image:  ["/Cars/Corolla 2007.jpg", "/Cars/detail1.jpg", "/Cars/detail3.jpg"], 
        image_thumbnail: "/Cars/detail1.jpg",
        image_thumbnail2: "/Cars/detail1.jpg",
        image_thumbnail3: "/Cars/detail1.jpg",
        video_id: "V06rNc5JcZw",
        name: "Black Corolla London 2007",
        description: "This is a well-maintained car with a clean history. It is fuel-efficient, offers a smooth driving experience, and has been well taken care of by its previous owners.",
        brand: "Toyota",
        feature: "no",
        Year: 2007,
        Mileage: "50,000 miles",
        engine: "2.0L, 4 Cylinder",
        priceCents: 700000000,
        agent_name: "Agent: James Emmanuel",
        agent_photo: "/Agents/agent1.jpg",
        agent_phone: "Phone: 0802307461",
        agent_email: "Email: james.emmanuel@example.com",
      },
      {
        id: "e43638ce-6aa0-4b85-b27f-e1d07eb6784r34wq",
        image_main: "/Cars/Corolla 2007.jpg",
        image:  ["/Cars/Corolla 2007.jpg", "/Cars/detail1.jpg", "/Cars/detail3.jpg"], 
        image_thumbnail: "/Cars/2.jpg",
        image_thumbnail2: "/Cars/detail1.jpg",
        image_thumbnail3: "/Cars/detail1.jpg",
        video_id: "V06rNc5JcZw",
        name: "Black Corolla London 2012",
        description: "This is a well-maintained car with a clean history. It is fuel-efficient, offers a smooth driving experience, and has been well taken care of by its previous owners.",
        brand: "Toyota",
        feature: "yes",
        Year: 2007,
        Mileage: "50,000 miles",
        engine: "2.0L, 4 Cylinder",
        priceCents: 700000000,
        agent_name: "Agent: James Emmanuel",
        agent_photo: "/Agents/agent1.jpg",
        agent_phone: "Phone: 0802307461",
        agent_email: "Email: james.emmanuel@example.com",
      },
];

// Add to product.js
export function trackProductView(productId) {
  const productToTrack = product.find(p => p.id === productId);
  if (!productToTrack) return;

  const recentViews = JSON.parse(localStorage.getItem('recentViews') || '[]');
  
  // Remove if already exists
  const existingIndex = recentViews.findIndex(v => v.id === productId);
  if (existingIndex >= 0) {
      recentViews.splice(existingIndex, 1);
  }

  // Add to beginning
  recentViews.unshift({
      id: productToTrack.id,
      name: productToTrack.name,
      image: productToTrack.image_main,
      timestamp: new Date().toISOString()
  });

  // Keep only last 10 views
  if (recentViews.length > 10) {
      recentViews.pop();
  }

  localStorage.setItem('recentViews', JSON.stringify(recentViews));
}

export default product;
// export { product };

